title: Rensselaer Repair Cafe

markdown: kramdown
enable-mathjax: yes

permalink: /blog/:title/

paginate: 8
paginate_path: /blog/page:num/

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag

exclude:
   - .jekyll-cache/
   - README.md
   - LICENSE
